version: '3.8'

services:
#  app:
#    container_name: javadev
#    build:
#      context: .
#      dockerfile: Dockerfile
#    environment:
#      # NOTE: POSTGRES_DB/USER/PASSWORD should match values in db container
#        POSTGRES_PASSWORD: postgres
#        POSTGRES_USER: postgres
#        POSTGRES_DB: postgres
#        POSTGRES_HOSTNAME: postgresdb

#    volumes:
#      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
#    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
#    network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    container_name: ktor_jimmer_postgresql
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - /data/docker-compose/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      # NOTE: POSTGRES_DB/USER/PASSWORD should match values in app container
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ktor_jimmer

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  consul:
    container_name: ktor_jimmer_consul
    image: consul:1.15.4
    restart: always
    ports:
      - "8500:8500"
    volumes:
      - /data/docker-compose/consul:/var/lib/consul/data
    command: [agent,-server,-ui,-client=0.0.0.0,-bootstrap-expect=1]

  redis:
    container_name: ktor_jimmer_redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /data/docker-compose/redis:/var/lib/redis/data